# permissions to do edit repositories.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: repository-editor-role
rules:
- apiGroups:
  - github.go.hein.dev
  resources:
  - repositories
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.go.hein.dev
  resources:
  - repositories/status
  verbs:
  - get
  - patch
  - update
