
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - github.go.hein.dev
  resources:
  - repositories
  - keys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - github.go.hein.dev
  resources:
  - repositories/status
  - keys/status
  verbs:
  - get
  - patch
  - update
